name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
        gemfile:
          - gemfiles/rubocop_1.48.gemfile
          - gemfiles/rubocop_1.49.gemfile
          - gemfiles/rubocop_1.50.gemfile
          - gemfiles/rubocop_1.51.gemfile
          - gemfiles/rubocop_1.52.gemfile
          - gemfiles/rubocop_1.53.gemfile
          - gemfiles/rubocop_1.54.gemfile
          - gemfiles/rubocop_1.55.gemfile
          - gemfiles/rubocop_1.56.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Test
      run: bundle exec rake
